import React, { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Mail, RefreshCw, Send, Trash2, X } from 'lucide-react';
import { AdminRole } from '../types';
import { answerUserMessage, deleteUserMessage, getAllUserMessages, UserMessage } from '../lib/userMessages';

interface AdminMessagesPageProps { currentAdminEmail: string; currentAdminRole: AdminRole; }

export const AdminMessagesPage: React.FC<AdminMessagesPageProps> = ({ currentAdminRole }) => {
  const [messages, setMessages] = useState<UserMessage[]>([]);
  const [status, setStatus] = useState<'all' | 'unanswered' | 'answered'>('all');
  const [selected, setSelected] = useState<UserMessage | null>(null);
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(true);
  const [deleteId, setDeleteId] = useState<string | null>(null);
  const canDelete = currentAdminRole === 'superadmin' || currentAdminRole === 'admin';

  const load = async () => { setLoading(true); try { setMessages(await getAllUserMessages()); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => messages.filter((message) => status === 'all' || message.status === status), [messages, status]);

  const open = (message: UserMessage) => { setSelected(message); setAnswer(message.answer || ''); };
  const submitAnswer = async (event: React.FormEvent) => { event.preventDefault(); if (!selected) return; await answerUserMessage(selected.id, answer); setSelected(null); await load(); };
  const remove = async () => { if (!deleteId) return; await deleteUserMessage(deleteId); setDeleteId(null); if (selected?.id === deleteId) setSelected(null); await load(); };

  return <div className="space-y-5">
    <div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-xs sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold text-[#8f1d2c]"><Mail className="h-4 w-4" />HỘP THƯ NGƯỜI DÙNG</div><h1 className="mt-1 text-xl font-bold text-[#0b2a4a]">CÂU HỎI NGƯỜI DÙNG</h1><p className="mt-1 text-xs text-slate-500">Tiếp nhận, trả lời và theo dõi trạng thái trao đổi.</p></div><button type="button" onClick={load} className="rounded-xl border border-slate-300 p-2.5 text-slate-600 hover:bg-slate-50"><RefreshCw className={loading ? 'h-4 w-4 animate-spin' : 'h-4 w-4'} /></button></div>
    <div className="flex gap-2 rounded-2xl border border-slate-200 bg-white p-3 shadow-xs"><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="rounded-lg border border-slate-300 px-3 py-2 text-xs"><option value="all">Tất cả trạng thái</option><option value="unanswered">Chưa trả lời</option><option value="answered">Đã trả lời</option></select><span className="self-center text-xs text-slate-500">{filtered.length} cuộc trao đổi</span></div>
    <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="bg-[#f4f7fb] text-[11px] font-bold uppercase text-slate-700"><tr><th className="p-3">Người dùng</th><th className="p-3">Câu hỏi</th><th className="p-3">Trạng thái</th><th className="p-3">Thời gian</th><th className="p-3 text-center">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((message) => <tr key={message.id} className="hover:bg-blue-50/30"><td className="p-3 font-semibold">{message.userEmail}</td><td className="max-w-md p-3"><button type="button" onClick={() => open(message)} className="line-clamp-2 text-left text-[#123b69] hover:underline">{message.question}</button></td><td className="p-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${message.status === 'answered' ? 'bg-emerald-100 text-emerald-800' : 'bg-amber-100 text-amber-800'}`}>{message.status === 'answered' ? 'Đã trả lời' : 'Chưa trả lời'}</span></td><td className="p-3 text-slate-500">{message.createdAt?.seconds ? new Date(message.createdAt.seconds * 1000).toLocaleString('vi-VN') : '—'}</td><td className="p-3 text-center"><div className="flex justify-center gap-2"><button type="button" onClick={() => open(message)} className="rounded p-1 text-[#123b69] hover:bg-blue-50" title="Mở"><Send className="h-3.5 w-3.5" /></button>{canDelete && <button type="button" onClick={() => setDeleteId(message.id)} className="rounded p-1 text-[#8f1d2c] hover:bg-rose-50" title="Xóa"><Trash2 className="h-3.5 w-3.5" /></button>}</div></td></tr>)}{!filtered.length && <tr><td colSpan={5} className="p-10 text-center text-slate-400">{loading ? 'Đang tải...' : 'Chưa có câu hỏi.'}</td></tr>}</tbody></table></div></div>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><form onSubmit={submitAnswer} className="w-full max-w-2xl space-y-4 rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><h2 className="font-bold text-[#0b2a4a]">Trao đổi với {selected.userEmail}</h2><button type="button" onClick={() => setSelected(null)}><X className="h-5 w-5 text-slate-400" /></button></div><div className="rounded-xl bg-blue-50 p-4 text-sm whitespace-pre-wrap">{selected.question}</div>{selected.answer && <div className="rounded-xl bg-emerald-50 p-4 text-sm whitespace-pre-wrap">{selected.answer}</div>}<textarea required maxLength={4000} value={answer} onChange={(event) => setAnswer(event.target.value)} rows={6} placeholder="Nhập câu trả lời..." className="w-full rounded-xl border border-slate-300 p-3 text-sm" /><div className="flex justify-end gap-2"><button type="button" onClick={() => setSelected(null)} className="rounded-lg border px-4 py-2 text-xs font-bold">Đóng</button><button type="submit" className="inline-flex items-center gap-2 rounded-lg bg-[#123b69] px-4 py-2 text-xs font-bold text-white"><CheckCircle2 className="h-4 w-4" />Gửi trả lời</button></div></form></div>}
    {deleteId && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div className="w-full max-w-sm space-y-4 rounded-2xl bg-white p-6 shadow-xl"><h2 className="font-bold text-[#8f1d2c]">Xác nhận xóa?</h2><p className="text-xs text-slate-600">Cuộc trao đổi sẽ bị xóa vĩnh viễn.</p><div className="flex justify-end gap-2"><button type="button" onClick={() => setDeleteId(null)} className="rounded-lg border px-4 py-2 text-xs font-bold">Hủy</button><button type="button" onClick={remove} className="rounded-lg bg-[#8f1d2c] px-4 py-2 text-xs font-bold text-white">Xóa</button></div></div></div>}
  </div>;
};
